import type {MpvChapter, MpvTrack} from '../../../../native';
import type {PlaylistEntry} from '../../../../store/slices/playerSlice';
import type {Playlist} from '../../../../types/playlist';
import type {TrackMetadata} from '../../../../services/metadataService';

type VideoV2PlaybackState = 'connecting' | 'ready' | 'playing' | 'paused' | 'buffering' | 'seeking' | 'finished' | 'error' | 'live';

type VideoV2Range = {start: number; end: number};

export interface VideoV2Model {
  colors: ReturnType<typeof import('../../../../theme').useTheme>['colors'];
  insets: {top: number; bottom: number; left: number; right: number};
  title: string;
  fileUri: string | null;
  nativePtr: number;
  showVideoSurface: boolean;
  playbackState: VideoV2PlaybackState;
  isPlaying: boolean;
  isBuffering: boolean;
  isSeeking: boolean;
  isEnded: boolean;
  isLive: boolean;
  position: number;
  duration: number;
  bufferedRanges: VideoV2Range[];
  isSeekable: boolean;
  controlsVisible: boolean;
  controlsLocked: boolean;
  isLandscape: boolean;
  volume: number;
  muted: boolean;
  speed: number;
  loopMode: 'none' | 'file' | 'playlist';
  shuffle: boolean;
  subtitleVisible: boolean;
  activeSubtitle: number | null;
  activeAudioTrack: number | null;
  subtitleFontSize: 'small' | 'medium' | 'large';
  subtitleOpacity: number;
  subtitlePosition: number;
  subtitleTextColor: string;
  subtitleBgOpacity: number;
  subtitles: MpvTrack[];
  audioTracks: MpvTrack[];
  chapters: MpvChapter[];
  queue: PlaylistEntry[];
  playlists: Playlist[];
  canAddToPlaylist: boolean;
  metadata: TrackMetadata | null;
  hasNext: boolean;
  hasPrevious: boolean;
  error: string | null;
  loadingMessage: string;
  showReplay: boolean;
  pipSupported: boolean;
  commands: {
    onSurfaceTap: () => void;
    onMinimize: () => void;
    onExpand: () => void;
    onPlayPause: () => void;
    onPrevious: () => void;
    onNext: () => void;
    onRewind: () => void;
    onForward: () => void;
    onSeek: (progress: number) => void;
    onToggleControlsLock: () => void;
    onToggleSubtitles: () => void;
    onToggleFullscreen: () => void;
    onEnterPip: () => void;
    onSelectPlaylist: (playlistId: string) => void;
    onCreatePlaylist: (name: string) => void;
    onSelectQueueItem: (uri: string) => void;
    onSelectChapter: (time: number) => void;
    onShare: () => void;
    onScreenshot: () => void;
    onRetry: () => void;
    onReplay: () => void;
    onVolumeChange: (volume: number) => void;
    onToggleMute: () => void;
    onSelectSubtitle: (trackId: number) => void;
    onChangeSubtitleFontSize: (size: 'small' | 'medium' | 'large') => void;
    onChangeSubtitleOpacity: (opacity: number) => void;
    onChangeSubtitlePosition: (position: number) => void;
    onChangeSubtitleTextColor: (color: string) => void;
    onChangeSubtitleBgOpacity: (opacity: number) => void;
    onSelectAudio: (trackId: number) => void;
    onSelectSpeed: (speed: number) => void;
    onToggleLoop: () => void;
    onToggleShuffle: () => void;
    onClose: () => void;
  };
}
